/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegexRouteImport } from './routes/regex'
import { Route as PdfRouteImport } from './routes/pdf'
import { Route as IcoRouteImport } from './routes/ico'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as Base64RouteImport } from './routes/base64'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RegexRoute = RegexRouteImport.update({
  id: '/regex',
  path: '/regex',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfRoute = PdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const IcoRoute = IcoRouteImport.update({
  id: '/ico',
  path: '/ico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64Route = Base64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/base64': typeof Base64Route
  '/convert': typeof ConvertRoute
  '/ico': typeof IcoRoute
  '/pdf': typeof PdfRoute
  '/regex': typeof RegexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/base64': typeof Base64Route
  '/convert': typeof ConvertRoute
  '/ico': typeof IcoRoute
  '/pdf': typeof PdfRoute
  '/regex': typeof RegexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/base64': typeof Base64Route
  '/convert': typeof ConvertRoute
  '/ico': typeof IcoRoute
  '/pdf': typeof PdfRoute
  '/regex': typeof RegexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/base64'
    | '/convert'
    | '/ico'
    | '/pdf'
    | '/regex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/base64' | '/convert' | '/ico' | '/pdf' | '/regex'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/base64'
    | '/convert'
    | '/ico'
    | '/pdf'
    | '/regex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  Base64Route: typeof Base64Route
  ConvertRoute: typeof ConvertRoute
  IcoRoute: typeof IcoRoute
  PdfRoute: typeof PdfRoute
  RegexRoute: typeof RegexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regex': {
      id: '/regex'
      path: '/regex'
      fullPath: '/regex'
      preLoaderRoute: typeof RegexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf': {
      id: '/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ico': {
      id: '/ico'
      path: '/ico'
      fullPath: '/ico'
      preLoaderRoute: typeof IcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64': {
      id: '/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof Base64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  Base64Route: Base64Route,
  ConvertRoute: ConvertRoute,
  IcoRoute: IcoRoute,
  PdfRoute: PdfRoute,
  RegexRoute: RegexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
